-- ============================================================
-- zonas_pago_distrito(zona_id, distrito_id)
-- Zona: tabla asumida zonas_pago(id autogenerado, nombre).
-- Asignaciones a nivel de cantón expandidas a todos sus distritos.
-- Correcciones aplicadas: Orotina y San Mateo -> PUNTARENAS; Río Cuarto -> SAN RAMÓN.
-- ============================================================

-- (Opcional) crear las zonas si no existen:
INSERT INTO zonas_pago (nombre) VALUES ('GAM');
INSERT INTO zonas_pago (nombre) VALUES ('GUANACASTE');
INSERT INTO zonas_pago (nombre) VALUES ('LIMÓN ABAJO');
INSERT INTO zonas_pago (nombre) VALUES ('PUNTARENAS');
INSERT INTO zonas_pago (nombre) VALUES ('QUEPOS');
INSERT INTO zonas_pago (nombre) VALUES ('SAN RAMÓN');
INSERT INTO zonas_pago (nombre) VALUES ('ZONA SUR');

-- Relación zona <-> distrito:
-- San José > San José
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Carmen' AND cantonId=(SELECT id FROM canton WHERE nombre='San José' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
-- San José > Aserrí
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Aserri' AND cantonId=(SELECT id FROM canton WHERE nombre='Aserrí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Salitrillos' AND cantonId=(SELECT id FROM canton WHERE nombre='Aserrí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
-- San José > Goicoechea
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Guadalupe' AND cantonId=(SELECT id FROM canton WHERE nombre='Goicoechea' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
-- San José > Tibás
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='San Juan' AND cantonId=(SELECT id FROM canton WHERE nombre='Tibás' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
-- San José > Curridabat
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Curridabat' AND cantonId=(SELECT id FROM canton WHERE nombre='Curridabat' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
-- San José > Pérez Zeledón
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='San Isidro de El General' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='El General' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Daniel Flores' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Rivas' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='San Pedro' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Platanares' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Pejibaye' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Cajón' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Barú' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Río Nuevo' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Páramo' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='La Amistad' AND cantonId=(SELECT id FROM canton WHERE nombre='Pérez Zeledón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='San José'))));
-- Alajuela > Alajuela
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Alajuela' AND cantonId=(SELECT id FROM canton WHERE nombre='Alajuela' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Tambor' AND cantonId=(SELECT id FROM canton WHERE nombre='Alajuela' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Alajuela > San Ramón
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='San Ramon' AND cantonId=(SELECT id FROM canton WHERE nombre='San Ramón' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Alajuela > San Mateo
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='San Mateo' AND cantonId=(SELECT id FROM canton WHERE nombre='San Mateo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Desmonte' AND cantonId=(SELECT id FROM canton WHERE nombre='San Mateo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Jesús María' AND cantonId=(SELECT id FROM canton WHERE nombre='San Mateo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Labrador' AND cantonId=(SELECT id FROM canton WHERE nombre='San Mateo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Alajuela > Orotina
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Orotina' AND cantonId=(SELECT id FROM canton WHERE nombre='Orotina' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='El Mastate' AND cantonId=(SELECT id FROM canton WHERE nombre='Orotina' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Hacienda Vieja' AND cantonId=(SELECT id FROM canton WHERE nombre='Orotina' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Coyolar' AND cantonId=(SELECT id FROM canton WHERE nombre='Orotina' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Ceiba' AND cantonId=(SELECT id FROM canton WHERE nombre='Orotina' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Alajuela > San Carlos
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Quesada' AND cantonId=(SELECT id FROM canton WHERE nombre='San Carlos' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Alajuela > Zarcero
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Zarcero' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Laguna' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Tapesco' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Guadalupe' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Palmira' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Zapote' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Brisas' AND cantonId=(SELECT id FROM canton WHERE nombre='Zarcero' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Alajuela > Río Cuarto
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Río Cuarto' AND cantonId=(SELECT id FROM canton WHERE nombre='Río Cuarto' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Santa Rita' AND cantonId=(SELECT id FROM canton WHERE nombre='Río Cuarto' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='SAN RAMÓN'), (SELECT id FROM distrito WHERE nombre='Santa Isabel' AND cantonId=(SELECT id FROM canton WHERE nombre='Río Cuarto' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Alajuela'))));
-- Cartago > Cartago
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Occidental' AND cantonId=(SELECT id FROM canton WHERE nombre='Cartago' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Cartago'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Tierra Blanca' AND cantonId=(SELECT id FROM canton WHERE nombre='Cartago' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Cartago'))));
-- Cartago > Paraíso
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Llanos de Santa Lucia' AND cantonId=(SELECT id FROM canton WHERE nombre='Paraíso' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Cartago'))));
-- Cartago > Oreamuno
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='San Rafael' AND cantonId=(SELECT id FROM canton WHERE nombre='Oreamuno' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Cartago'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GAM'), (SELECT id FROM distrito WHERE nombre='Potrero Cerrado' AND cantonId=(SELECT id FROM canton WHERE nombre='Oreamuno' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Cartago'))));
-- Heredia > Sarapiquí
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Puerto Viejo' AND cantonId=(SELECT id FROM canton WHERE nombre='Sarapiquí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Heredia'))));
-- Guanacaste > Liberia
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Liberia' AND cantonId=(SELECT id FROM canton WHERE nombre='Liberia' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Cañas Dulces' AND cantonId=(SELECT id FROM canton WHERE nombre='Liberia' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Mayorga' AND cantonId=(SELECT id FROM canton WHERE nombre='Liberia' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Nacascolo' AND cantonId=(SELECT id FROM canton WHERE nombre='Liberia' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Curubandé' AND cantonId=(SELECT id FROM canton WHERE nombre='Liberia' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
-- Guanacaste > Carrillo
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Filadelfia' AND cantonId=(SELECT id FROM canton WHERE nombre='Carrillo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Palmira' AND cantonId=(SELECT id FROM canton WHERE nombre='Carrillo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Sardinal' AND cantonId=(SELECT id FROM canton WHERE nombre='Carrillo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Belén' AND cantonId=(SELECT id FROM canton WHERE nombre='Carrillo' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
-- Guanacaste > Nandayure
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Carmona' AND cantonId=(SELECT id FROM canton WHERE nombre='Nandayure' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Santa Rita' AND cantonId=(SELECT id FROM canton WHERE nombre='Nandayure' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Zapotal' AND cantonId=(SELECT id FROM canton WHERE nombre='Nandayure' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='San Pablo' AND cantonId=(SELECT id FROM canton WHERE nombre='Nandayure' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Porvenir' AND cantonId=(SELECT id FROM canton WHERE nombre='Nandayure' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='GUANACASTE'), (SELECT id FROM distrito WHERE nombre='Bejuco' AND cantonId=(SELECT id FROM canton WHERE nombre='Nandayure' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Guanacaste'))));
-- Puntarenas > Puntarenas
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Puntarenas' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Pitahaya' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Chomes' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Lepanto' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Paquera' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Manzanillo' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Guacimal' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Barranca' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Isla del Coco' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Cóbano' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Chacarita' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Chira' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Acapulco' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='El Roble' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Arancibia' AND cantonId=(SELECT id FROM canton WHERE nombre='Puntarenas' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Buenos Aires
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Buenos Aires' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Volcán' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Potrero Grande' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Boruca' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Pilas' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Colinas' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Chánguena' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Biolley' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Brunka' AND cantonId=(SELECT id FROM canton WHERE nombre='Buenos Aires' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Montes de Oro
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='Miramar' AND cantonId=(SELECT id FROM canton WHERE nombre='Montes de Oro' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='La Unión' AND cantonId=(SELECT id FROM canton WHERE nombre='Montes de Oro' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='PUNTARENAS'), (SELECT id FROM distrito WHERE nombre='San Isidro' AND cantonId=(SELECT id FROM canton WHERE nombre='Montes de Oro' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Osa
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Puerto Cortés' AND cantonId=(SELECT id FROM canton WHERE nombre='Osa' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Palmar' AND cantonId=(SELECT id FROM canton WHERE nombre='Osa' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Sierpe' AND cantonId=(SELECT id FROM canton WHERE nombre='Osa' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Bahía Ballena' AND cantonId=(SELECT id FROM canton WHERE nombre='Osa' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Piedras Blancas' AND cantonId=(SELECT id FROM canton WHERE nombre='Osa' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Bahía Drake' AND cantonId=(SELECT id FROM canton WHERE nombre='Osa' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Quepos
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Quepos' AND cantonId=(SELECT id FROM canton WHERE nombre='Quepos' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Savegre' AND cantonId=(SELECT id FROM canton WHERE nombre='Quepos' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Naranjito' AND cantonId=(SELECT id FROM canton WHERE nombre='Quepos' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Golfito
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Golfito' AND cantonId=(SELECT id FROM canton WHERE nombre='Golfito' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Guaycará' AND cantonId=(SELECT id FROM canton WHERE nombre='Golfito' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Pavón' AND cantonId=(SELECT id FROM canton WHERE nombre='Golfito' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Parrita
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Parrita' AND cantonId=(SELECT id FROM canton WHERE nombre='Parrita' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Corredores
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Corredor' AND cantonId=(SELECT id FROM canton WHERE nombre='Corredores' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='La Cuesta' AND cantonId=(SELECT id FROM canton WHERE nombre='Corredores' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Canoas' AND cantonId=(SELECT id FROM canton WHERE nombre='Corredores' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Laurel' AND cantonId=(SELECT id FROM canton WHERE nombre='Corredores' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Garabito
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Jacó' AND cantonId=(SELECT id FROM canton WHERE nombre='Garabito' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Tárcoles' AND cantonId=(SELECT id FROM canton WHERE nombre='Garabito' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='QUEPOS'), (SELECT id FROM distrito WHERE nombre='Lagunillas' AND cantonId=(SELECT id FROM canton WHERE nombre='Garabito' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Puntarenas > Puerto Jiménez
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='ZONA SUR'), (SELECT id FROM distrito WHERE nombre='Puerto Jiménez' AND cantonId=(SELECT id FROM canton WHERE nombre='Puerto Jiménez' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Puntarenas'))));
-- Limón > Pococí
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Guápiles' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Jiménez' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Rita' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Roxana' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Cariari' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='Colorado' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));
INSERT INTO zonas_pago_distrito (zona_id, distrito_id) VALUES ((SELECT id FROM zonas_pago WHERE nombre='LIMÓN ABAJO'), (SELECT id FROM distrito WHERE nombre='La Colonia' AND cantonId=(SELECT id FROM canton WHERE nombre='Pococí' AND provinciaId=(SELECT id FROM provincia WHERE nombre='Limón'))));